##
# this program prints 100 numbers generated by a random number generator.
#

def main():
    count = 1
    rOld = int(input("\n> random starting number = "))
    while count < 101:
        rOld = randomGenerator(rOld)
        print(rOld, end='')
        if count < 100:
            print(', ', end='')
        if count % 10 == 0:
            print()
        count += 1


def randomGenerator(r, a=32310901, b=1729, m=224):
    return (a * r + b) % m


if __name__ == '__main__':
    main()
